apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rancher-rbac.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: cluster-api-provider-evroc
    app.kubernetes.io/component: rancher-integration
