# This rule is not used by the project cluster-api-provider-evroc itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to infrastructure.evroc.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-evroc
    app.kubernetes.io/managed-by: kustomize
  name: evrocmachinetemplate-viewer-role
rules:
- apiGroups:
  - infrastructure.evroc.com
  resources:
  - evrocmachinetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.evroc.com
  resources:
  - evrocmachinetemplates/status
  verbs:
  - get
